### PR TITLE
Add name to the API key (optional)

### PR DESCRIPTION
**Pull request by treemo**
Add name to the API key (optional) to help administration of multiple API keys

### CODE REVIEW

**Comment by mrtolkien** [comment]
Hi! That indeed sounds like a nice feature.

I've cleaned up the project so could you add tests for this feature so we keep 100% test coverage? The tests will automatically run when you add commits to this branch.

Thanks a lot!

**Comment by mrtolkien** [comment]
Could you add unit tests for the `name` feature? Just a simple test making sure it behaves as expected would help the project keep 100% test coverage!

image

**Comment by treemo** [comment]
Hi!

I added functional tests on this feature and the 'never_expires' parameter, normally now there is better test coverage :)
The unit tests are not launched automatically? (this allows to check if everything is correct), I am used to the CI of Gitlab and the launch are systematic and automatic.

---

For information, normally in the REST API the action types correspond to specific methods:
- GET Retrieve information about the REST API resource
- POST Create a REST API resource
- PUT Update a REST API resource
- DELETE Delete a REST API resource or related component

Currently, all actions are made in GET

**Comment by mrtolkien** [comment]
> The unit tests are not launched automatically?

They need approval to be run if you're a first time contributor to a project!

Everything looks good and I took the time to cleanup the project a little bit so contributing is easier. Thanks for your help!

**Comment by treemo** [comment]
Ha ok :)

Thanks and have a nice day

**Pull request merged**
