### PR TITLE
improved endpoitnt documentation

### PR DESCRIPTION
**Pull request by fboerman**
converted endpoint arguments to proper query to have openapi docs display it correctly

### CODE REVIEW

**Comment by mrtolkien** [comment]
Looks good, thanks!

**Comment by fboerman** [comment]
hi @mrtolkien wow that was fast haha. are you also going to put a new release out for it or gonna wait for it? btw to help with releases I can also help you setup a github action for it.

**Comment by mrtolkien** [comment]
Releases are just `poetry publish --build` for me so that wouldn't save much time, but it's always welcome!

I'll push a `1.0.1` release with the new documentation.

**Comment by fboerman** [comment]
> Releases are just `poetry publish --build` for me so that wouldn't save much time, but it's always welcome!
> 
> I'll push a `1.0.1` release with the new documentation.

ah okay yeah thats hard to beat indeed :P Thanks!

**Pull request merged**
